from exercicio_class_teste_de_objetos import pessoas

pessoa_1 = pessoas("luiz", 23)
pessoa_2 = pessoas("maria", 43)

print(pessoa_1.nome)
print(pessoa_1.idade)

pessoa_1.comecar_comer("banana")
pessoa_1.status()
pessoa_1.comecar_comer("pessego")
pessoa_1.status()
pessoa_1.parar_comer()
pessoa_1.status()
pessoa_1.parar_comer()
pessoa_1.status()
pessoa_1.falar("python")
pessoa_1.status()
pessoa_1.comecar_comer("laranja")
pessoa_1.status()
pessoa_1.falar("linguagem")
pessoa_1.parar_comer()
pessoa_1.status()
pessoa_1.falar("qualquer coisa")
pessoa_1.status()
pessoa_1.parar_falar()
pessoa_1.status()
pessoa_1.comecar_comer("laranjas")
pessoa_1.status()
pessoa_1.parar_falar()
pessoa_1.parar_comer()
pessoa_2.comecar_comer("pizza")
pessoa_1.comecar_comer("banana")
pessoa_2.parar_comer()
pessoa_1.falar("assunto")

print(pessoa_1.get_ano_de_nascimento())
print(pessoa_2.get_ano_de_nascimento())